dynamicrequests/config/routes.rb
Rails.application.routes.draw do
  resources :request_types
  resources :requests
  root "requests#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

dynamicrequests/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

dynamicrequests/app/models/request.rb
class Request < ApplicationRecord
  belongs_to :request_type
	serialize :properties, Hash
end

dynamicrequests/app/models/request_field.rb
class RequestField < ApplicationRecord
  belongs_to :request_type
end

dynamicrequests/app/models/request_type.rb
class RequestType < ApplicationRecord
  has_many :fields, class_name: "RequestField", dependent: :destroy
	accepts_nested_attributes_for :fields, reject_if: :all_blank, allow_destroy: true
  has_many :requests, dependent: :destroy
end

dynamicrequests/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

dynamicrequests/app/controllers/request_types_controller.rb
class RequestTypesController < ApplicationController
  before_action :set_request_type, only: %i[ show edit update destroy ]

  # GET /request_types or /request_types.json
  def index
    @request_types = RequestType.all
  end

  # GET /request_types/1 or /request_types/1.json
  def show
  end

  # GET /request_types/new
  def new
    @request_type = RequestType.new
  end

  # GET /request_types/1/edit
  def edit
  end

  # POST /request_types or /request_types.json
  def create
    @request_type = RequestType.new(request_type_params)

    respond_to do |format|
      if @request_type.save
        format.html { redirect_to @request_type, notice: "Request type was successfully created." }
        format.json { render :show, status: :created, location: @request_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @request_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /request_types/1 or /request_types/1.json
  def update
    respond_to do |format|
      if @request_type.update(request_type_params)
        format.html { redirect_to @request_type, notice: "Request type was successfully updated." }
        format.json { render :show, status: :ok, location: @request_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @request_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /request_types/1 or /request_types/1.json
  def destroy
    @request_type.destroy
    respond_to do |format|
      format.html { redirect_to request_types_url, notice: "Request type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request_type
      @request_type = RequestType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def request_type_params
      params.require(:request_type).permit(:name, fields_attributes:[:id, :field_type, :name, :required, :_destroy])
    end
end

dynamicrequests/app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: %i[ show edit update destroy ]

  # GET /requests or /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1 or /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new(request_type_id: params[:request_type_id])
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests or /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: "Request was successfully created." }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1 or /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: "Request was successfully updated." }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1 or /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: "Request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def request_params
      params.require(:request).permit(:name, :request_type_id, properties:{})
    end
end

dynamicrequests/app/helpers/application_helper.rb
module ApplicationHelper
end

dynamicrequests/app/helpers/request_types_helper.rb
module RequestTypesHelper
end

dynamicrequests/app/helpers/requests_helper.rb
module RequestsHelper
end

dynamicrequests/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dynamicrequests</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

dynamicrequests/app/views/request_types/_field_fields.html.erb
<fieldset class="nested-fields">
    <%= f.select :field_type, %w[text_field check_box] %>
    <%= f.text_field :name, palceholder: "field_name" %>
    <%= f.check_box :required %><%= f.label :required %>
    <%= link_to_remove_association "Remove Field", f %>
</fieldset>

dynamicrequests/app/views/request_types/_form.html.erb
<%= form_with(model: request_type) do |form| %>
  <% if request_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request_type.errors.count, "error") %> prohibited this request_type from being saved:</h2>

      <ul>
        <% request_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <%= form.fields_for :fields do |builder| %>
      <%= render 'field_fields', f: builder %>
  <% end %>
  <div class="links">
      <%= link_to_add_association "Add Field", form, :fields %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

dynamicrequests/app/views/request_types/edit.html.erb
<h1>Editing Request Type</h1>

<%= render 'form', request_type: @request_type %>

<%= link_to 'Show', @request_type %> |
<%= link_to 'Back', request_types_path %>

dynamicrequests/app/views/request_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Request Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @request_types.each do |request_type| %>
      <tr>
        <td><%= request_type.name %></td>
        <td><%= link_to 'Show', request_type %></td>
        <td><%= link_to 'Edit', edit_request_type_path(request_type) %></td>
        <td><%= link_to 'Destroy', request_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request Type', new_request_type_path %>

dynamicrequests/app/views/request_types/new.html.erb
<h1>New Request Type</h1>

<%= render 'form', request_type: @request_type %>

<%= link_to 'Back', request_types_path %>

dynamicrequests/app/views/request_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @request_type.name %>
</p>

<%= link_to 'Edit', edit_request_type_path(@request_type) %> |
<%= link_to 'Back', request_types_path %>

dynamicrequests/app/views/requests/_form.html.erb
<%= form_with(model: request) do |form| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
        <% request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :request_type_id %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <%= form.fields_for :properties, OpenStruct.new(@request.properties) do |builder| %>
    <% @request.request_type.fields.each do |field| %>
      <%= render "requests/fields/#{field.field_type}", field: field, f: builder %>
    <% end %>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

dynamicrequests/app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

dynamicrequests/app/views/requests/fields/_check_box.html.erb
<div class="field">
    <%= f.check_box field.name[-1]=="?" ? field.name + " " : field.name %>
    <%= f.label field.name %>
</div>

dynamicrequests/app/views/requests/fields/_text_field.html.erb
<div class="field">
    <%= f.label field.name %>
    <%= f.text_field field.name[-1]=="?" ? field.name + " " : field.name %>
</div>

dynamicrequests/app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.name %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= form_tag new_request_path, method: :get do %>
  <%= select_tag :request_type_id, options_from_collection_for_select(RequestType.all, :id, :name) %>
  <%= submit_tag "New Request", name: nil %>
<% end %>

dynamicrequests/app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Back', requests_path %>

dynamicrequests/app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @request.name %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>